### ISSUE TITLE
The start playback method isn't being called.

### ISSUE THREAD

**Issue by fbernardo** [PubStation/PubStation-tvOS-SDK#1]
`interstitialAdManager(manager: PSInterstitialAdManager!, didStartAdPlayback ad: PSInterstitialAd!)` isn't being called. I tried with your SwiftDemo example and it never hit's the breakpoint.

Our application has background audio, that needs to be disabled while playing the interstitial. The start playback seems like the perfect place for that.

**Comment by jansaputra** [comment]
Hi Fábio, thank you a lot for letting us know! Probably this is a bug, I will check that myself and update you as soon as possible.

**Comment by jansaputra** [comment]
The bug should be fixed now, I just updated the SDK and the SwiftDemo example. Can you check please if it works now for you? Thanks! :)

**Comment by fbernardo** [comment]
It is. Thank you. 👍

**Comment by jansaputra** [comment]
You are welcome! 👍  And thank you for letting us know again. If other issues appear or if you have any questions, do not hesitate to ask again.
